name: Deploy to Render and Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      checks: write
    environment: ${{ github.event_name == 'pull_request' && 'Preview' || 'Production' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip deploy for pull requests
        if: github.event_name == 'pull_request'
        run: echo "Pull request detected. Skipping Render/Vercel deploy. Check satisfied."

      - name: Mark required check as success
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Deploy to Render and Vercel / deploy',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Deploy skipped for pull_request',
                summary: 'Check satisfied without running Render/Vercel deploy.'
              }
            })

      - name: Trigger Render deploy
        if: github.event_name != 'pull_request'
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          if [ -z "$RENDER_SERVICE_ID" ] || [ -z "$RENDER_API_KEY" ]; then
            echo "Render secrets not configured. Skipping Render deploy."
            exit 0
          fi

          curl --fail-with-body -X POST \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{}' \
            "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys"

      - name: Trigger Vercel deploy
        if: github.event_name != 'pull_request'
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$VERCEL_DEPLOY_HOOK_URL" ]; then
            echo "Vercel deploy hook URL not configured. Skipping Vercel deploy."
            exit 0
          fi

          curl -fsS -X POST "$VERCEL_DEPLOY_HOOK_URL"
